version: "2"

services:
    web_console:
        image: bitbull/docker-exec-web-console
        environment:
        - 'CONTEXT_PATH=/web-console/'
        read_only: true
        restart: always
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    nginx:
        image: nginx:latest
        read_only: true
        restart: always
        extra_hosts: 
            - "dockerhost:192.168.0.14"
        ports:
        - 8083:80
        volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        - /var/cache/nginx/
        - /var/run/
        - ./logs/:/logs/
